# Generated by Django 3.2.6 on 2022-03-04 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='transfer',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='balance',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='operation',
            field=models.CharField(choices=[('refill', 'refill'), ('withdraw', 'withdraw'), ('transfer', 'transfer')], max_length=30, verbose_name='Тип операции'),
        ),
    ]
